import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import heroImage from "/public/static/hero-image.png";
import Banner from "../../component/banner";
import Card from "../../component/card";
import coffeeStoresData from "../../data/coffee-stores.json";

export default function Home(props: Record<string, Record<string, string>[]>) {
  const { coffeeStores } = props;
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Store Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.heroContainer}>
          <Banner
            buttonText={"View stores nearby"}
            handleOnClick={handleOnBannerBtnClick}
          />
          <Image
            className={styles.heroImage}
            src={heroImage}
            alt="illustration of person drinking coffee"
            placeholder="blur"
            width={700}
            height={400}
            fill={false}
          />
          <h2 className={styles.h2}>Coffee stores Landing Page</h2>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps(context: unknown) {
  return {
    props: {
      coffeeStores: coffeeStoresData,
    }, // will be passed to the page component as props
  };
}
